package msc.ai.collaborativedesk.ui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import msc.ai.collaborativedesk.core.managers.PanelManager;
import msc.ai.collaborativedesk.ui.panel.DocumentListPanel;
import msc.ai.collaborativedesk.ui.panel.DocumentQueue;
import msc.ai.collaborativedesk.ui.panel.TeamChatPanel;
import msc.ai.collaborativedesk.ui.panel.UploadDocumentPanel;

/**
 *
 * @author Keshan De Silva
 */
public class CollaborativeDesk extends javax.swing.JFrame
{

    /**
     * Creates new form NewMDIApplication
     */
    public CollaborativeDesk()
    {
        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        }
        catch (Exception ex)
        {
            Logger.getLogger(CollaborativeDesk.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        btnDocumentManager.setVisible(false);
        separatorDocumentManager.setVisible(false);
        btnDocumentQueue.setVisible(false);
        separatorDocumentQueue.setVisible(false);
        PanelManager.getInstance().init(desktopPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnTaskList = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDocumentManager = new javax.swing.JButton();
        separatorDocumentManager = new javax.swing.JToolBar.Separator();
        btnDocumentQueue = new javax.swing.JButton();
        separatorDocumentQueue = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Collaborative Desk");

        jToolBar1.setFloatable(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Team.png"))); // NOI18N
        jButton5.setText("Team");
        jButton5.setFocusable(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton5.setMaximumSize(new java.awt.Dimension(135, 39));
        jButton5.setMinimumSize(new java.awt.Dimension(135, 39));
        jButton5.setPreferredSize(new java.awt.Dimension(135, 39));
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator5);

        btnTaskList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Task.png"))); // NOI18N
        btnTaskList.setText("Task Manager");
        btnTaskList.setToolTipText("");
        btnTaskList.setFocusable(false);
        btnTaskList.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnTaskList.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnTaskList.setMaximumSize(new java.awt.Dimension(135, 39));
        btnTaskList.setMinimumSize(new java.awt.Dimension(135, 39));
        btnTaskList.setPreferredSize(new java.awt.Dimension(135, 39));
        btnTaskList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnTaskListActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTaskList);
        jToolBar1.add(jSeparator1);

        btnDocumentManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Documents.png"))); // NOI18N
        btnDocumentManager.setText("Document Manager");
        btnDocumentManager.setFocusable(false);
        btnDocumentManager.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDocumentManager.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDocumentManagerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDocumentManager);
        jToolBar1.add(separatorDocumentManager);

        btnDocumentQueue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Queue.png"))); // NOI18N
        btnDocumentQueue.setText("Document Queue");
        btnDocumentQueue.setFocusable(false);
        btnDocumentQueue.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDocumentQueue.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDocumentQueueActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDocumentQueue);
        jToolBar1.add(separatorDocumentQueue);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Log.png"))); // NOI18N
        jButton4.setText("Activity Log");
        jButton4.setToolTipText("");
        jButton4.setFocusable(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton4.setMaximumSize(new java.awt.Dimension(135, 39));
        jButton4.setMinimumSize(new java.awt.Dimension(135, 39));
        jButton4.setPreferredSize(new java.awt.Dimension(135, 39));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaskListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnTaskListActionPerformed
    {//GEN-HEADEREND:event_btnTaskListActionPerformed
//        JInternalFrame frame = new JInternalFrame("Task Details", true, true, true, true );
//        frame.setSize(700, 400);
//        TaskListPanel panel = new TaskListPanel();
//        frame.setLayout(new BorderLayout());
//        frame.add(panel, BorderLayout.CENTER);
//        desktopPane.add(frame);
//        frame.setVisible(true);  
        
        PanelManager.getInstance().showPanel(PanelManager.InternalPanelID.TASK_LIST_PANEL, true);
        PanelManager.getInstance().getPanel(PanelManager.InternalPanelID.TASK_LIST_PANEL).update();
    }//GEN-LAST:event_btnTaskListActionPerformed

    private void btnDocumentManagerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDocumentManagerActionPerformed
    {//GEN-HEADEREND:event_btnDocumentManagerActionPerformed
        JInternalFrame frame = new JInternalFrame("Document List", true, true, true, true );
        frame.setSize(700, 400);
        DocumentListPanel panel = new DocumentListPanel();
        frame.setLayout(new BorderLayout());
        frame.add(panel, BorderLayout.CENTER);
        desktopPane.add(frame);
        frame.setVisible(true); 
    }//GEN-LAST:event_btnDocumentManagerActionPerformed

    private void btnDocumentQueueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDocumentQueueActionPerformed
    {//GEN-HEADEREND:event_btnDocumentQueueActionPerformed
        JInternalFrame frame = new JInternalFrame("Document Queue", true, true, true, true );
        frame.setSize(700, 400);
        DocumentQueue panel = new DocumentQueue();
        frame.setLayout(new BorderLayout());
        frame.add(panel, BorderLayout.CENTER);
        desktopPane.add(frame);
        frame.setVisible(true);
    }//GEN-LAST:event_btnDocumentQueueActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
//        JInternalFrame frame = new JInternalFrame("Create Task", true, true, true, true );
//        frame.setSize(700, 400);
//        CreateTaskPanel panel = new CreateTaskPanel();
//        frame.setLayout(new BorderLayout());
//        frame.add(panel, BorderLayout.CENTER);
//        desktopPane.add(frame);
//        frame.setVisible(true);  
//        
//        JInternalFrame frame1 = new JInternalFrame("Upload Document", true, true, true, true );
//        frame1.setSize(700, 400);
//        UploadDocumentPanel panel1 = new UploadDocumentPanel();
//        frame1.setLayout(new BorderLayout());
//        frame1.add(panel1, BorderLayout.CENTER);
//        desktopPane.add(frame1);
//        frame1.setVisible(true); 
//        
//        JInternalFrame frame2 = new JInternalFrame("Team Chat", true, true, true, true );
//        frame2.setSize(700, 400);
//        TeamChatPanel panel2 = new TeamChatPanel();
//        frame2.setLayout(new BorderLayout());
//        frame2.add(panel2, BorderLayout.CENTER);
//        desktopPane.add(frame2);
//        frame2.setVisible(true);  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton4MouseClicked
    {//GEN-HEADEREND:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        PanelManager.getInstance().showPanel(PanelManager.InternalPanelID.MEMBER_LIST_PANEL, true); 
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocumentManager;
    private javax.swing.JButton btnDocumentQueue;
    private javax.swing.JButton btnTaskList;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar.Separator separatorDocumentManager;
    private javax.swing.JToolBar.Separator separatorDocumentQueue;
    // End of variables declaration//GEN-END:variables

}
