package msc.ai.collaborativedesk.ui;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import msc.ai.collaborativedesk.core.managers.DatabaseManager;
import msc.ai.collaborativedesk.core.managers.DeskManager;
import msc.ai.collaborativedesk.core.managers.PanelManager;
import msc.ai.collaborativedesk.ui.panel.DocumentListPanel;

/**
 *
 * @author Keshan De Silva
 */
public class CollaborativeDeskAdministrator extends javax.swing.JFrame
{

    public CollaborativeDeskAdministrator()
    {
        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        }
        catch (Exception ex)
        {
            Logger.getLogger(CollaborativeDesk.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        btnDocument.setVisible(false);
        separatorDocument.setVisible(false);
        
        PanelManager.getInstance().init(desktopPane);
        DeskManager.getIntance().syncUserList(DatabaseManager.getIntance().getUsers());
        DeskManager.getIntance().syncTaskList(DatabaseManager.getIntance().getTask());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnUserList = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDocument = new javax.swing.JButton();
        separatorDocument = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Collaborative Desk - Administration");

        jToolBar1.setFloatable(false);

        btnUserList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Users.png"))); // NOI18N
        btnUserList.setText("Users");
        btnUserList.setFocusable(false);
        btnUserList.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnUserList.setMaximumSize(new java.awt.Dimension(135, 39));
        btnUserList.setMinimumSize(new java.awt.Dimension(135, 39));
        btnUserList.setPreferredSize(new java.awt.Dimension(135, 39));
        btnUserList.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUserListActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUserList);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator1);

        btnDocument.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Documents.png"))); // NOI18N
        btnDocument.setText("Document Manager");
        btnDocument.setFocusable(false);
        btnDocument.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDocument.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDocumentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDocument);
        jToolBar1.add(separatorDocument);
        jToolBar1.add(jSeparator4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocumentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDocumentActionPerformed
    {//GEN-HEADEREND:event_btnDocumentActionPerformed
        JInternalFrame frame = new JInternalFrame("Document List", true, true, true, true );
        frame.setSize(700, 400);
        DocumentListPanel panel = new DocumentListPanel();
        frame.setLayout(new BorderLayout());
        frame.add(panel, BorderLayout.CENTER);
        desktopPane.add(frame);
        frame.setVisible(true); 
    }//GEN-LAST:event_btnDocumentActionPerformed

    private void btnUserListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUserListActionPerformed
    {//GEN-HEADEREND:event_btnUserListActionPerformed
        PanelManager.getInstance().showPanel(PanelManager.InternalPanelID.USER_LIST_PANEL, true);
    }//GEN-LAST:event_btnUserListActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocument;
    private javax.swing.JButton btnUserList;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar.Separator separatorDocument;
    // End of variables declaration//GEN-END:variables

}
