package msc.ai.collaborativedesk.ui.panel;

import java.util.ArrayList;
import javax.swing.JInternalFrame;
import msc.ai.collaborativedesk.core.managers.DatabaseManager;
import msc.ai.collaborativedesk.core.managers.DeskManager;
import msc.ai.collaborativedesk.core.managers.PanelManager;
import msc.ai.collaborativedesk.model.dao.User;
import msc.ai.collaborativedesk.ui.model.UserListTableModel;

/**
 *
 * @author Keshan De Silva
 */
public class TeamMembersPanel extends javax.swing.JPanel implements InternalPanel
{
    private static TeamMembersPanel instance;
    private UserListTableModel tableModel;
    
    private TeamMembersPanel()
    {
        initComponents();
    }
    
    public static TeamMembersPanel getInstance()
    {
        if (instance == null)
        {
            instance = new TeamMembersPanel();
        }
        return instance;
            
    }
    
    @Override
    public void init()
    {
        tableModel = new UserListTableModel();
        memberListTable.setModel(tableModel);
        
        memberListTable.getColumnModel().getColumn(0).setMinWidth(0);
        memberListTable.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    @Override
    public void update()
    {
        DeskManager deskManager = DeskManager.getIntance();
        ArrayList<User> userList = deskManager.getUserList();
        tableModel.setUserList(userList);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        memberListTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnStartChat = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Team"));

        memberListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(memberListTable);

        btnStartChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Send.png"))); // NOI18N
        btnStartChat.setText("Start Conversasion");
        btnStartChat.setMinimumSize(new java.awt.Dimension(91, 23));
        btnStartChat.setPreferredSize(new java.awt.Dimension(91, 25));
        btnStartChat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartChatActionPerformed(evt);
            }
        });

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/collaborativedesk/resources/Export.jpg"))); // NOI18N
        btnExport.setText("Export");
        btnExport.setMinimumSize(new java.awt.Dimension(91, 23));
        btnExport.setPreferredSize(new java.awt.Dimension(91, 25));
        btnExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStartChat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExportActionPerformed
    {//GEN-HEADEREND:event_btnExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnStartChatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartChatActionPerformed
    {//GEN-HEADEREND:event_btnStartChatActionPerformed
        if ( memberListTable.getSelectedRow() != -1 )
        {
            int row = memberListTable.getSelectedRow();
            User selectedUser = tableModel.getUserList().get(row);
            
            PanelManager.getInstance().getChatPanel(selectedUser, DeskManager.getIntance().getUser());
            JInternalFrame frame = PanelManager.getInstance().getChatFrame(selectedUser, DeskManager.getIntance().getUser());
            
            frame.setVisible(true);  
        }
    }//GEN-LAST:event_btnStartChatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnStartChat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable memberListTable;
    // End of variables declaration//GEN-END:variables
}
